[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "cd server && npm install --legacy-peer-deps && cd .."
]

[phases.build]
cmds = ["CI=false npm run build"]

[start]
cmd = "npm run server"

